#pragma once
#include "../src/preprocessor/preprocessor_token.hpp"
#include "../src/preprocessor/token.hpp"
#include <string>
using namespace std;
inline string token_to_string(const Token &token) {
  switch (token.tag) {
  case TokenTag::INT:
    return to_string(token.as.INT);
  case TokenTag::FLOAT:
    return to_string(token.as.FLOAT);
  case TokenTag::SYMBOL:
    return resolve_symbol(token.as.SYMBOL);
  case TokenTag::STRING:
    return "\"" + resolve_interned_string(token.as.STR) + "\"";
  case TokenTag::LET:
    return "let";
  case TokenTag::SET:
    return "set";
  case TokenTag::AT:
    return "at";
  case TokenTag::IF:
    return "if";
  case TokenTag::ELIF:
    return "elif";
  case TokenTag::ELSE:
    return "else";
  case TokenTag::FUNCTION:
    return "function";
  case TokenTag::TRY:
    return "try";
  case TokenTag::EXPECT:
    return "expect";
  case TokenTag::ASSIGN:
    return "=";
  case TokenTag::BROPEN:
    return "(";
  case TokenTag::BRCLOSE:
    return ")";
  case TokenTag::CURLOPEN:
    return "{";
  case TokenTag::CURLCLOSE:
    return "}";
  case TokenTag::COMMA:
    return ",";
  case TokenTag::DOT:
    return ".";
  case TokenTag::BAR:
    return "|";
  case TokenTag::OP_ADD:
    return "+";
  case TokenTag::OP_SUB:
    return "-";
  case TokenTag::OP_MUL:
    return "*";
  case TokenTag::OP_DIV:
    return "/";
  case TokenTag::OP_MOD:
    return "mod";
  case TokenTag::OP_EQ:
    return "==";
  case TokenTag::OP_NEQ:
    return "!=";
  case TokenTag::OP_NOT:
    return "not";
  case TokenTag::OP_OR:
    return "or";
  case TokenTag::OP_AND:
    return "and";
  case TokenTag::OPERATOR_LT:
    return "<";
  case TokenTag::OPERATOR_LTE:
    return "<=";
  case TokenTag::OPERATOR_GT:
    return ">";
  case TokenTag::OPERATOR_GTE:
    return ">=";
  case TokenTag::OPERATOR_STRCONCAT:
    return "<>";
  case TokenTag::IDENTIFIER:
    return resolve_interned_string(token.as.IDENTIFIER);
  case TokenTag::RETURN:
    return "return";
  }
}
inline string pptoken_to_string(const PreprocessorToken &token) {
  switch (token.tag) {
  case PpTokenTag::INT:
    return to_string(token.as.INT);
  case PpTokenTag::FLOAT:
    return to_string(token.as.FLOAT);
  case PpTokenTag::SYMBOL:
    return resolve_symbol(token.as.SYMBOL);
  case PpTokenTag::STRING:
    return "\"" + resolve_interned_string(token.as.STR) + "\"";
  case PpTokenTag::LET:
    return "let";
  case PpTokenTag::SET:
    return "set";
  case PpTokenTag::AT:
    return "at";
  case PpTokenTag::IF:
    return "if";
  case PpTokenTag::ELIF:
    return "elif";
  case PpTokenTag::ELSE:
    return "else";
  case PpTokenTag::FUNCTION:
    return "function";
  case PpTokenTag::TRY:
    return "try";
  case PpTokenTag::EXPECT:
    return "expect";
  case PpTokenTag::ASSIGN:
    return "=";
  case PpTokenTag::BROPEN:
    return "(";
  case PpTokenTag::BRCLOSE:
    return ")";
  case PpTokenTag::CURLOPEN:
    return "{";
  case PpTokenTag::CURLCLOSE:
    return "}";
  case PpTokenTag::COMMA:
    return ",";
  case PpTokenTag::DOT:
    return ".";
  case PpTokenTag::BAR:
    return "|";
  case PpTokenTag::OP_ADD:
    return "+";
  case PpTokenTag::OP_SUB:
    return "-";
  case PpTokenTag::OP_MUL:
    return "*";
  case PpTokenTag::OP_DIV:
    return "/";
  case PpTokenTag::OP_MOD:
    return "mod";
  case PpTokenTag::OP_EQ:
    return "==";
  case PpTokenTag::OP_NEQ:
    return "!=";
  case PpTokenTag::OP_NOT:
    return "not";
  case PpTokenTag::OP_OR:
    return "or";
  case PpTokenTag::OP_AND:
    return "and";
  case PpTokenTag::OPERATOR_LT:
    return "<";
  case PpTokenTag::OPERATOR_LTE:
    return "<=";
  case PpTokenTag::OPERATOR_GT:
    return ">";
  case PpTokenTag::OPERATOR_GTE:
    return ">=";
  case PpTokenTag::OPERATOR_STRCONCAT:
    return "<>";
  case PpTokenTag::IDENTIFIER:
    return resolve_interned_string(token.as.IDENTIFIER);
  case PpTokenTag::RETURN:
    return "return";
  case PpTokenTag::INCLUDE_MACRO:
    return "MACRO(-include)";
  case PpTokenTag::DEFINE_MACRO:
    return "MACRO(-define)";
  case PpTokenTag::FSET_MACRO:
    return "MACRO(-fset)";
  case PpTokenTag::FUNSET_MACRO:
    return "MACRO(-funset)";
  case PpTokenTag::IFFSET_MACRO:
    return "MACRO(-iffset)";
  case PpTokenTag::IFNFSET_MACRO:
    return "MACRO(-ifnfset)";
  case PpTokenTag::ENDIF_MACRO:
    return "MACRO(-endif)";
  }
}
