#include "../lib/asap/t.hpp"
#include "../src/parser/node.hpp"
#include "../src/parser/parser.hpp"
#include "../src/preprocessor/preprocess.hpp"
#include "../src/preprocessor/preprocessor_tokenize.hpp"
#include "testutil_mask_nodes.hpp"
#include "testutil_node_to_string.hpp"
using namespace std;
namespace {
static string filename = "test.msl";
string parse_and_show(string code) {
  auto pptokens = preprocessor_tokenize(&filename, code);
  IncludedModules mods;
  auto tokens = preprocess_pptokens(filename, &mods, pptokens, true);
  auto n = parse(tokens);
  string out = "First Item = " + to_string(n.first_elem) + "\n\n";
  for (size_t i = 0; i < n.elements.size(); i++) {
    Node node = n.elements.at(i);
    out += to_string(i);
    out += " ";
    out += show_node(node);
    out += "-----------------------\n";
  }
  auto masking = create_mask(&n);
  out += "MASK: ";
  for (bool m : masking) {
    if (m) {
      out += "$ ";
    } else {
      out += "_ ";
    }
  }
  out += "\n";
  return out;
}
void test_literal(T *t) {
  string code = "4 \"hello\" #to #mom 3.5";
  string out = parse_and_show(code);
  t->assert_str_eq(out, "First Item = 1\n\n"
                        "0 Node  NIL:\n"
                        "    Start = NIL\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "1 Node  LITERAL_INT = 4:\n"
                        "    Start = test.msl/1/1\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 2\n"
                        "-----------------------\n"
                        "2 Node  LITERAL_STRING = 'hello':\n"
                        "    Start = test.msl/1/3\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 3\n"
                        "-----------------------\n"
                        "3 Node  LITERAL_SYMBOL = #to:\n"
                        "    Start = test.msl/1/11\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 4\n"
                        "-----------------------\n"
                        "4 Node  LITERAL_SYMBOL = #mom:\n"
                        "    Start = test.msl/1/15\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 5\n"
                        "-----------------------\n"
                        "5 Node  LITERAL_FLOAT = 3.500000:\n"
                        "    Start = test.msl/1/20\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "MASK: $ $ $ $ $ $ \n");
}
void test_var_def(T *t) {
  string code = "let x = 1 5";
  string out = parse_and_show(code);
  t->assert_str_eq(out, "First Item = 1\n\n"
                        "0 Node  NIL:\n"
                        "    Start = NIL\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "1 Node  VAR_DEF = x:\n"
                        "    Start = test.msl/1/1\n"
                        "    First_Child = 2\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 3\n"
                        "-----------------------\n"
                        "2 Node  LITERAL_INT = 1:\n"
                        "    Start = test.msl/1/9\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "3 Node  LITERAL_INT = 5:\n"
                        "    Start = test.msl/1/11\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "MASK: $ $ $ $ \n");
}
void test_group_and_prefix_operator(T *t) {
  string code = "not [ 5 ]";
  string out = parse_and_show(code);
  t->assert_str_eq(out, "First Item = 1\n"
                        "\n"
                        "0 Node  NIL:\n"
                        "    Start = NIL\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "1 Node  NOT:\n"
                        "    Start = test.msl/1/1\n"
                        "    First_Child = 2\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "2 Node  LITERAL_INT = 5:\n"
                        "    Start = test.msl/1/7\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "MASK: $ $ $ \n");
}
void test_add(T *t) {
  string code = "1 + b";
  string out = parse_and_show(code);
  t->assert_str_eq(out, "First Item = 2\n"
                        "\n"
                        "0 Node  NIL:\n"
                        "    Start = NIL\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "1 Node  LITERAL_INT = 1:\n"
                        "    Start = test.msl/1/1\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 3\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "2 Node  INFIX(+):\n"
                        "    Start = test.msl/1/3\n"
                        "    First_Child = 1\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "3 Node  VAR_REF = b:\n"
                        "    Start = test.msl/1/5\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "MASK: $ $ $ $ \n");
}
void test_fn_call(T *t) {
  string code = "do_stuff(1, b)";
  string out = parse_and_show(code);
  t->assert_str_eq(out, "First Item = 2\n"
                        "\n"
                        "0 Node  NIL:\n"
                        "    Start = NIL\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "1 Node  VAR_REF = do_stuff:\n"
                        "    Start = test.msl/1/1\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 3\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "2 Node  FN_CALL:\n"
                        "    Start = test.msl/1/1\n"
                        "    First_Child = 1\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "3 Node  LITERAL_INT = 1:\n"
                        "    Start = test.msl/1/10\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 4\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "4 Node  VAR_REF = b:\n"
                        "    Start = test.msl/1/13\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "MASK: $ $ $ $ $ \n");
}
void test_fn_call_2(T *t) {
  string code = "a + do_stuff(1, b)";
  string out = parse_and_show(code);
  t->assert_str_eq(out, "First Item = 2\n"
                        "\n"
                        "0 Node  NIL:\n"
                        "    Start = NIL\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "1 Node  VAR_REF = a:\n"
                        "    Start = test.msl/1/1\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 4\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "2 Node  INFIX(+):\n"
                        "    Start = test.msl/1/3\n"
                        "    First_Child = 1\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "3 Node  VAR_REF = do_stuff:\n"
                        "    Start = test.msl/1/5\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 5\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "4 Node  FN_CALL:\n"
                        "    Start = test.msl/1/5\n"
                        "    First_Child = 3\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "5 Node  LITERAL_INT = 1:\n"
                        "    Start = test.msl/1/14\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 6\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "6 Node  VAR_REF = b:\n"
                        "    Start = test.msl/1/17\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "MASK: $ $ $ $ $ $ $ \n");
}
void test_if(T *t) {
  string code = "if(#true) { print(\"hello\") }";
  string out = parse_and_show(code);
  t->assert_str_eq(out, "First Item = 1\n"
                        "\n"
                        "0 Node  NIL:\n"
                        "    Start = NIL\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "1 Node  IF:\n"
                        "    Start = test.msl/1/1\n"
                        "    First_Child = 2\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "2 Node  PARTIAL_CONDITION:\n"
                        "    Start = test.msl/1/1\n"
                        "    First_Child = 3\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "3 Node  LITERAL_SYMBOL = #true:\n"
                        "    Start = test.msl/1/4\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 5\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "4 Node  VAR_REF = print:\n"
                        "    Start = test.msl/1/13\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 6\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "5 Node  FN_CALL:\n"
                        "    Start = test.msl/1/13\n"
                        "    First_Child = 4\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "6 Node  LITERAL_STRING = 'hello':\n"
                        "    Start = test.msl/1/19\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "MASK: $ $ $ $ $ $ $ \n");
}
void test_if_else(T *t) {
  string code = "if(#true) { #ok } else { #notok }";
  string out = parse_and_show(code);
  t->assert_str_eq(out, "First Item = 1\n"
                        "\n"
                        "0 Node  NIL:\n"
                        "    Start = NIL\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "1 Node  IF:\n"
                        "    Start = test.msl/1/1\n"
                        "    First_Child = 2\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "2 Node  PARTIAL_CONDITION:\n"
                        "    Start = test.msl/1/1\n"
                        "    First_Child = 3\n"
                        "    Next_Child = 5\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "3 Node  LITERAL_SYMBOL = #true:\n"
                        "    Start = test.msl/1/4\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 4\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "4 Node  LITERAL_SYMBOL = #ok:\n"
                        "    Start = test.msl/1/13\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "5 Node  PARTIAL_DEFAULT_CONDITION:\n"
                        "    Start = test.msl/1/19\n"
                        "    First_Child = 6\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "6 Node  LITERAL_SYMBOL = #notok:\n"
                        "    Start = test.msl/1/26\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "MASK: $ $ $ $ $ $ $ \n");
}
void test_if_elif_elif_else(T *t) {
  string code = "if(#true) { #if_block }\n"
                "elif(#false) { #first_elif_block }\n"
                "elif(#lol) { #second_elif_block }\n"
                "else { #else_block }";
  string out = parse_and_show(code);
  t->assert_str_eq(out, "First Item = 1\n"
                        "\n"
                        "0 Node  NIL:\n"
                        "    Start = NIL\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "1 Node  IF:\n"
                        "    Start = test.msl/1/1\n"
                        "    First_Child = 2\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "2 Node  PARTIAL_CONDITION:\n"
                        "    Start = test.msl/1/1\n"
                        "    First_Child = 3\n"
                        "    Next_Child = 5\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "3 Node  LITERAL_SYMBOL = #true:\n"
                        "    Start = test.msl/1/4\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 4\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "4 Node  LITERAL_SYMBOL = #if_block:\n"
                        "    Start = test.msl/1/13\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "5 Node  PARTIAL_CONDITION:\n"
                        "    Start = test.msl/2/1\n"
                        "    First_Child = 6\n"
                        "    Next_Child = 8\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "6 Node  LITERAL_SYMBOL = #false:\n"
                        "    Start = test.msl/2/6\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 7\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "7 Node  LITERAL_SYMBOL = #first_elif_block:\n"
                        "    Start = test.msl/2/16\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "8 Node  PARTIAL_CONDITION:\n"
                        "    Start = test.msl/3/1\n"
                        "    First_Child = 9\n"
                        "    Next_Child = 11\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "9 Node  LITERAL_SYMBOL = #lol:\n"
                        "    Start = test.msl/3/6\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 10\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "10 Node  LITERAL_SYMBOL = #second_elif_block:\n"
                        "    Start = test.msl/3/14\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "11 Node  PARTIAL_DEFAULT_CONDITION:\n"
                        "    Start = test.msl/4/1\n"
                        "    First_Child = 12\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "12 Node  LITERAL_SYMBOL = #else_block:\n"
                        "    Start = test.msl/4/8\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "MASK: $ $ $ $ $ $ $ $ $ $ $ $ $ \n");
}
void test_function(T *t) {
  string code = "function add(a,b){\n"
                "a + b\n"
                "}";
  string out = parse_and_show(code);
  t->assert_str_eq(out, "First Item = 1\n"
                        "\n"
                        "0 Node  NIL:\n"
                        "    Start = NIL\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "1 Node  FN_DEF = add:\n"
                        "    Start = test.msl/1/1\n"
                        "    First_Child = 2\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "2 Node  LIST:\n"
                        "    Start = test.msl/1/13\n"
                        "    First_Child = 3\n"
                        "    Next_Child = 6\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "3 Node  VAR_REF = a:\n"
                        "    Start = test.msl/1/14\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 4\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "4 Node  VAR_REF = b:\n"
                        "    Start = test.msl/1/16\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "5 Node  VAR_REF = a:\n"
                        "    Start = test.msl/2/1\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 7\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "6 Node  INFIX(+):\n"
                        "    Start = test.msl/2/3\n"
                        "    First_Child = 5\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "7 Node  VAR_REF = b:\n"
                        "    Start = test.msl/2/5\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "MASK: $ $ $ $ $ $ $ $ \n");
}
void test_function_no_args(T *t) {
  string code = "function void(){ }";
  string out = parse_and_show(code);
  t->assert_str_eq(out, "First Item = 1\n"
                        "\n"
                        "0 Node  NIL:\n"
                        "    Start = NIL\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "1 Node  FN_DEF = void:\n"
                        "    Start = test.msl/1/1\n"
                        "    First_Child = 2\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "2 Node  LIST:\n"
                        "    Start = test.msl/1/14\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "MASK: $ $ $ \n");
}
void test_function_returns(T *t) {
  string code = "function does_return(){ return not #true }";
  string out = parse_and_show(code);
  t->assert_str_eq(out, "First Item = 1\n"
                        "\n"
                        "0 Node  NIL:\n"
                        "    Start = NIL\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "1 Node  FN_DEF = does_return:\n"
                        "    Start = test.msl/1/1\n"
                        "    First_Child = 2\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "2 Node  LIST:\n"
                        "    Start = test.msl/1/21\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 3\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "3 Node  RETURN:\n"
                        "    Start = test.msl/1/25\n"
                        "    First_Child = 4\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "4 Node  NOT:\n"
                        "    Start = test.msl/1/32\n"
                        "    First_Child = 5\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "5 Node  LITERAL_SYMBOL = #true:\n"
                        "    Start = test.msl/1/36\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "MASK: $ $ $ $ $ $ \n");
}
void test_function_left_apply(T *t) {
  string code = "a . add(1)";
  string out = parse_and_show(code);
  t->assert_str_eq(out, "First Item = 2\n"
                        "\n"
                        "0 Node  NIL:\n"
                        "    Start = NIL\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "1 Node  VAR_REF = a:\n"
                        "    Start = test.msl/1/1\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 4\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "2 Node  FN_CALL:\n"
                        "    Start = test.msl/1/5\n"
                        "    First_Child = 3\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "3 Node  VAR_REF = add:\n"
                        "    Start = test.msl/1/5\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 1\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "4 Node  LITERAL_INT = 1:\n"
                        "    Start = test.msl/1/9\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "MASK: $ $ $ $ $ \n");
}
void test_function_right_apply(T *t) {
  string code = "a | add(1)";
  string out = parse_and_show(code);
  t->assert_str_eq(out, "First Item = 2\n"
                        "\n"
                        "0 Node  NIL:\n"
                        "    Start = NIL\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "1 Node  VAR_REF = a:\n"
                        "    Start = test.msl/1/1\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "2 Node  FN_CALL:\n"
                        "    Start = test.msl/1/5\n"
                        "    First_Child = 3\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "3 Node  VAR_REF = add:\n"
                        "    Start = test.msl/1/5\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 4\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "4 Node  LITERAL_INT = 1:\n"
                        "    Start = test.msl/1/9\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 1\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "MASK: $ $ $ $ $ \n");
}

void test_list(T *t) {
  string code = "list() list(1,2,3) list(1)";
  string out = parse_and_show(code);
  t->assert_str_eq(out, "First Item = 2\n"
                        "\n"
                        "0 Node  NIL:\n"
                        "    Start = NIL\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "1 Node  VAR_REF = list:\n"
                        "    Start = test.msl/1/1\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "2 Node  FN_CALL:\n"
                        "    Start = test.msl/1/1\n"
                        "    First_Child = 1\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 4\n"
                        "-----------------------\n"
                        "3 Node  VAR_REF = list:\n"
                        "    Start = test.msl/1/8\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 5\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "4 Node  FN_CALL:\n"
                        "    Start = test.msl/1/8\n"
                        "    First_Child = 3\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 9\n"
                        "-----------------------\n"
                        "5 Node  LITERAL_INT = 1:\n"
                        "    Start = test.msl/1/13\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 6\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "6 Node  LITERAL_INT = 2:\n"
                        "    Start = test.msl/1/15\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 7\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "7 Node  LITERAL_INT = 3:\n"
                        "    Start = test.msl/1/17\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "8 Node  VAR_REF = list:\n"
                        "    Start = test.msl/1/20\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 10\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "9 Node  FN_CALL:\n"
                        "    Start = test.msl/1/20\n"
                        "    First_Child = 8\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "10 Node  LITERAL_INT = 1:\n"
                        "    Start = test.msl/1/25\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "MASK: $ $ $ $ $ $ $ $ $ $ $ \n");
}

void test_list_get(T *t) {
  string code = "at(mylist,0)";
  string out = parse_and_show(code);
  t->assert_str_eq(out, "First Item = 2\n"
                        "\n"
                        "0 Node  NIL:\n"
                        "    Start = NIL\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "1 Node  VAR_REF = at:\n"
                        "    Start = test.msl/1/1\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 3\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "2 Node  FN_CALL:\n"
                        "    Start = test.msl/1/1\n"
                        "    First_Child = 1\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "3 Node  VAR_REF = mylist:\n"
                        "    Start = test.msl/1/4\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 4\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "4 Node  LITERAL_INT = 0:\n"
                        "    Start = test.msl/1/11\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "MASK: $ $ $ $ $ \n");
}
void test_list_set(T *t) {
  string code = "put(mylist,0,1)";
  string out = parse_and_show(code);
  t->assert_str_eq(out, "First Item = 2\n"
                        "\n"
                        "0 Node  NIL:\n"
                        "    Start = NIL\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "1 Node  VAR_REF = put:\n"
                        "    Start = test.msl/1/1\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 3\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "2 Node  FN_CALL:\n"
                        "    Start = test.msl/1/1\n"
                        "    First_Child = 1\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "3 Node  VAR_REF = mylist:\n"
                        "    Start = test.msl/1/5\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 4\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "4 Node  LITERAL_INT = 0:\n"
                        "    Start = test.msl/1/12\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 5\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "5 Node  LITERAL_INT = 1:\n"
                        "    Start = test.msl/1/14\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "MASK: $ $ $ $ $ $ \n");
}

void test_try(T *t) {
  string code = "try print(#hi) + 1";
  string out = parse_and_show(code);
  t->assert_str_eq(out, "First Item = 5\n"
                        "\n"
                        "0 Node  NIL:\n"
                        "    Start = NIL\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "1 Node  TRY:\n"
                        "    Start = test.msl/1/1\n"
                        "    First_Child = 3\n"
                        "    Next_Child = 6\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "2 Node  VAR_REF = print:\n"
                        "    Start = test.msl/1/5\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 4\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "3 Node  FN_CALL:\n"
                        "    Start = test.msl/1/5\n"
                        "    First_Child = 2\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "4 Node  LITERAL_SYMBOL = #hi:\n"
                        "    Start = test.msl/1/11\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "5 Node  INFIX(+):\n"
                        "    Start = test.msl/1/16\n"
                        "    First_Child = 1\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "6 Node  LITERAL_INT = 1:\n"
                        "    Start = test.msl/1/18\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "MASK: $ $ $ $ $ $ $ \n");
}

void test_expect(T *t) {
  string code = "expect print(#hi) + 1";
  string out = parse_and_show(code);
  t->assert_str_eq(out, "First Item = 5\n"
                        "\n"
                        "0 Node  NIL:\n"
                        "    Start = NIL\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "1 Node  EXPECT:\n"
                        "    Start = test.msl/1/1\n"
                        "    First_Child = 3\n"
                        "    Next_Child = 6\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "2 Node  VAR_REF = print:\n"
                        "    Start = test.msl/1/8\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 4\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "3 Node  FN_CALL:\n"
                        "    Start = test.msl/1/8\n"
                        "    First_Child = 2\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "4 Node  LITERAL_SYMBOL = #hi:\n"
                        "    Start = test.msl/1/14\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "5 Node  INFIX(+):\n"
                        "    Start = test.msl/1/19\n"
                        "    First_Child = 1\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "6 Node  LITERAL_INT = 1:\n"
                        "    Start = test.msl/1/21\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "MASK: $ $ $ $ $ $ $ \n");
}
void test_no_args_fn_call(T *t) {
  string code = "1 . print()";
  string out = parse_and_show(code);
  t->assert_str_eq(out, "First Item = 2\n"
                        "\n"
                        "0 Node  NIL:\n"
                        "    Start = NIL\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "1 Node  LITERAL_INT = 1:\n"
                        "    Start = test.msl/1/1\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "2 Node  FN_CALL:\n"
                        "    Start = test.msl/1/5\n"
                        "    First_Child = 3\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "3 Node  VAR_REF = print:\n"
                        "    Start = test.msl/1/5\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 1\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "MASK: $ $ $ $ \n");
}
void test_for_loop(T *t) {
  string code = "for x in somelist{\n"
                "#noop\n"
                "}";
  string out = parse_and_show(code);
  t->assert_str_eq(out, "First Item = 1\n"
                        "\n"
                        "0 Node  NIL:\n"
                        "    Start = NIL\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "1 Node  FOR x:\n"
                        "    Start = test.msl/1/1\n"
                        "    First_Child = 2\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "2 Node  VAR_REF = somelist:\n"
                        "    Start = test.msl/1/10\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 3\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "3 Node  LITERAL_SYMBOL = #noop:\n"
                        "    Start = test.msl/2/1\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "MASK: $ $ $ $ \n");
}

void test_fn_call_3(T *t) {
  string code = "function add_and_print(a,b){ \n"
                "  print(a)\n"
                "  print(b)\n"
                "  return a + b\n"
                "}\n"
                "print(add_and_print(6,99))\n";
  string out = parse_and_show(code);
  t->assert_str_eq(out, "First Item = 1\n"
                        "\n"
                        "0 Node  NIL:\n"
                        "    Start = NIL\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "1 Node  FN_DEF = add_and_print:\n"
                        "    Start = test.msl/1/1\n"
                        "    First_Child = 2\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 16\n"
                        "-----------------------\n"
                        "2 Node  LIST:\n"
                        "    Start = test.msl/1/23\n"
                        "    First_Child = 3\n"
                        "    Next_Child = 6\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "3 Node  VAR_REF = a:\n"
                        "    Start = test.msl/1/24\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 4\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "4 Node  VAR_REF = b:\n"
                        "    Start = test.msl/1/26\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "5 Node  VAR_REF = print:\n"
                        "    Start = test.msl/2/3\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 7\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "6 Node  FN_CALL:\n"
                        "    Start = test.msl/2/3\n"
                        "    First_Child = 5\n"
                        "    Next_Child = 9\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "7 Node  VAR_REF = a:\n"
                        "    Start = test.msl/2/9\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "8 Node  VAR_REF = print:\n"
                        "    Start = test.msl/3/3\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 10\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "9 Node  FN_CALL:\n"
                        "    Start = test.msl/3/3\n"
                        "    First_Child = 8\n"
                        "    Next_Child = 11\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "10 Node  VAR_REF = b:\n"
                        "    Start = test.msl/3/9\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "11 Node  RETURN:\n"
                        "    Start = test.msl/4/3\n"
                        "    First_Child = 13\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "12 Node  VAR_REF = a:\n"
                        "    Start = test.msl/4/10\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 14\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "13 Node  INFIX(+):\n"
                        "    Start = test.msl/4/12\n"
                        "    First_Child = 12\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "14 Node  VAR_REF = b:\n"
                        "    Start = test.msl/4/14\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "15 Node  VAR_REF = print:\n"
                        "    Start = test.msl/6/1\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 18\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "16 Node  FN_CALL:\n"
                        "    Start = test.msl/6/1\n"
                        "    First_Child = 15\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "17 Node  VAR_REF = add_and_print:\n"
                        "    Start = test.msl/6/7\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 19\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "18 Node  FN_CALL:\n"
                        "    Start = test.msl/6/7\n"
                        "    First_Child = 17\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "19 Node  LITERAL_INT = 6:\n"
                        "    Start = test.msl/6/21\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 20\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "20 Node  LITERAL_INT = 99:\n"
                        "    Start = test.msl/6/23\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "MASK: $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ \n");
}

} // namespace
int main() {
  T t("Parser");
  t.test("literal values", test_literal);
  t.test("var def", test_var_def);
  t.test("group and prefix operator", test_group_and_prefix_operator);
  t.test("add", test_add);
  t.test("fn-call", test_fn_call);
  t.test("if", test_if);
  t.test("if-else", test_if_else);
  t.test("if-elif-elif-else", test_if_elif_elif_else);
  t.test("function", test_function);
  t.test("function no args", test_function_no_args);
  t.test("function with return", test_function_returns);
  t.test("function left apply", test_function_left_apply);
  t.test("function right apply", test_function_right_apply);
  t.test("function call after operator?", test_fn_call_2);
  t.test("function call with args used", test_fn_call_3);
  t.test("list", test_list);
  t.test("get list element", test_list_get);
  t.test("put list element", test_list_set);
  t.test("try", test_try);
  t.test("expect", test_expect);
  t.test("no-args fn call", test_no_args_fn_call);
  t.test("for-loop", test_for_loop);
  return 0;
}
