#include "../lib/asap/t.hpp"
#include "../src/parser/node.hpp"
#include "../src/parser/parser.hpp"
#include "../src/preprocessor/preprocess.hpp"
#include "../src/preprocessor/preprocessor_tokenize.hpp"
#include "testutil_node_to_string.hpp"
#include "testutil_mask_nodes.hpp"
using namespace std;
namespace {
static string filename = "test.msl";
string parse_and_show(string code) {
  auto pptokens = preprocessor_tokenize(filename, code);
  IncludedModules mods;
  auto tokens = preprocess_pptokens(filename, &mods, pptokens);
  auto n = parse(tokens);
  string out = "First Item = " + to_string(n.first_elem) + "\n\n";
  for (auto node : n.elements) {
    out += show_node(node);
    out += "-----------------------\n";
  }
  auto masking = create_mask(&n);
  out += "MASK: ";
  for (bool m : masking) {
    if (m) {
      out += "$ ";
    } else {
      out += "_ ";
    }
  }
  out += "\n";
  return out;
}
void test_literal(T *t) {
  string code = "4 \"hello\" #to #mom 3.5";
  string out = parse_and_show(code);
  t->assert_str_eq(out, "First Item = 1\n\n"
                        "Node  NIL:\n"
                        "    Start = NIL\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  LITERAL_INT = 4:\n"
                        "    Start = test.msl/0/2\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 2\n"
                        "-----------------------\n"
                        "Node  LITERAL_STRING = 'hello':\n"
                        "    Start = test.msl/0/4\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 3\n"
                        "-----------------------\n"
                        "Node  LITERAL_SYMBOL = #to:\n"
                        "    Start = test.msl/0/12\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 4\n"
                        "-----------------------\n"
                        "Node  LITERAL_SYMBOL = #mom:\n"
                        "    Start = test.msl/0/16\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 5\n"
                        "-----------------------\n"
                        "Node  LITERAL_FLOAT = 3.500000:\n"
                        "    Start = test.msl/0/21\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "MASK: $ $ $ $ $ $ \n"

  );
}
void test_var_def(T *t) {
  string code = "let x = 1 5";
  string out = parse_and_show(code);
  t->assert_str_eq(out, "First Item = 1\n\n"
                        "Node  NIL:\n"
                        "    Start = NIL\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  VAR_DEF = x:\n"
                        "    Start = test.msl/0/2\n"
                        "    First_Child = 2\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 3\n"
                        "-----------------------\n"
                        "Node  LITERAL_INT = 1:\n"
                        "    Start = test.msl/0/10\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  LITERAL_INT = 5:\n"
                        "    Start = test.msl/0/12\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "MASK: $ $ $ $ \n");
}
void test_group_and_prefix_operator(T *t) {
  string code = "not ( 5 )";
  string out = parse_and_show(code);
  t->assert_str_eq(out, "First Item = 1\n"
                        "\n"
                        "Node  NIL:\n"
                        "    Start = NIL\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  NOT:\n"
                        "    Start = test.msl/0/2\n"
                        "    First_Child = 2\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  LITERAL_INT = 5:\n"
                        "    Start = test.msl/0/8\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "MASK: $ $ $ \n");
}
void test_add(T *t) {
  string code = "1 + b";
  string out = parse_and_show(code);
  t->assert_str_eq(out, "First Item = 2\n"
                        "\n"
                        "Node  NIL:\n"
                        "    Start = NIL\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  LITERAL_INT = 1:\n"
                        "    Start = test.msl/0/2\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 3\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  INFIX(+):\n"
                        "    Start = test.msl/0/4\n"
                        "    First_Child = 1\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  VAR_REF = b:\n"
                        "    Start = test.msl/0/6\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "MASK: $ $ $ $ \n");
}
void test_fn_call(T *t) {
  string code = "do_stuff(1, b)";
  string out = parse_and_show(code);
  t->assert_str_eq(out, "First Item = 2\n"
                        "\n"
                        "Node  NIL:\n"
                        "    Start = NIL\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  VAR_REF = do_stuff:\n"
                        "    Start = test.msl/0/2\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 3\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  FN_CALL:\n"
                        "    Start = test.msl/0/2\n"
                        "    First_Child = 1\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  LITERAL_INT = 1:\n"
                        "    Start = test.msl/0/11\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 4\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  VAR_REF = b:\n"
                        "    Start = test.msl/0/14\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "MASK: $ $ $ $ $ \n");
}
void test_fn_call_2(T *t) {
  string code = "a + do_stuff(1, b)";
  string out = parse_and_show(code);
  t->assert_str_eq(out, "First Item = 2\n"
                        "\n"
                        "Node  NIL:\n"
                        "    Start = NIL\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  VAR_REF = a:\n"
                        "    Start = test.msl/0/2\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 4\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  INFIX(+):\n"
                        "    Start = test.msl/0/4\n"
                        "    First_Child = 1\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  VAR_REF = do_stuff:\n"
                        "    Start = test.msl/0/6\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 5\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  FN_CALL:\n"
                        "    Start = test.msl/0/6\n"
                        "    First_Child = 3\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  LITERAL_INT = 1:\n"
                        "    Start = test.msl/0/15\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 6\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  VAR_REF = b:\n"
                        "    Start = test.msl/0/18\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "MASK: $ $ $ $ $ $ $ \n"

  );
}
void test_if(T *t) {
  string code = "if(#true) { print(\"hello\") }";
  string out = parse_and_show(code);
  t->assert_str_eq(out, "First Item = 1\n"
                        "\n"
                        "Node  NIL:\n"
                        "    Start = NIL\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  IF:\n"
                        "    Start = test.msl/0/2\n"
                        "    First_Child = 2\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  PARTIAL_CONDITION:\n"
                        "    Start = test.msl/0/2\n"
                        "    First_Child = 3\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  LITERAL_SYMBOL = #true:\n"
                        "    Start = test.msl/0/5\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 5\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  VAR_REF = print:\n"
                        "    Start = test.msl/0/14\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 6\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  FN_CALL:\n"
                        "    Start = test.msl/0/14\n"
                        "    First_Child = 4\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  LITERAL_STRING = 'hello':\n"
                        "    Start = test.msl/0/20\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "MASK: $ $ $ $ $ $ $ \n");
}
void test_if_elif_elif_else(T *t) {
  string code = "if(#true) { #if_block }\n"
                "elif(#false) { #first_elif_block }\n"
                "elif(#lol) { #second_elif_block }\n"
                "else { #else_block }";
  string out = parse_and_show(code);
  t->assert_str_eq(out, "First Item = 1\n"
                        "\n"
                        "Node  NIL:\n"
                        "    Start = NIL\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  IF:\n"
                        "    Start = test.msl/0/2\n"
                        "    First_Child = 2\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  PARTIAL_CONDITION:\n"
                        "    Start = test.msl/0/2\n"
                        "    First_Child = 3\n"
                        "    Next_Child = 5\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  LITERAL_SYMBOL = #true:\n"
                        "    Start = test.msl/0/5\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 4\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  LITERAL_SYMBOL = #if_block:\n"
                        "    Start = test.msl/0/14\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  PARTIAL_CONDITION:\n"
                        "    Start = test.msl/1/2\n"
                        "    First_Child = 6\n"
                        "    Next_Child = 8\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  LITERAL_SYMBOL = #false:\n"
                        "    Start = test.msl/1/7\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 7\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  LITERAL_SYMBOL = #first_elif_block:\n"
                        "    Start = test.msl/1/17\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  PARTIAL_CONDITION:\n"
                        "    Start = test.msl/2/2\n"
                        "    First_Child = 9\n"
                        "    Next_Child = 11\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  LITERAL_SYMBOL = #lol:\n"
                        "    Start = test.msl/2/7\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 10\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  LITERAL_SYMBOL = #second_elif_block:\n"
                        "    Start = test.msl/2/15\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  PARTIAL_DEFAULT_CONDITION:\n"
                        "    Start = test.msl/3/2\n"
                        "    First_Child = 12\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  LITERAL_SYMBOL = #else_block:\n"
                        "    Start = test.msl/3/9\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "MASK: $ $ $ $ $ $ $ $ $ $ $ $ $ \n"

  );
}
void test_function(T *t) {
  string code = "function add(a,b){\n"
                "a + b\n"
                "}";
  string out = parse_and_show(code);
  t->assert_str_eq(out, "First Item = 1\n"
                        "\n"
                        "Node  NIL:\n"
                        "    Start = NIL\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  FUNCTION = add:\n"
                        "    Start = test.msl/0/2\n"
                        "    First_Child = 2\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  LIST:\n"
                        "    Start = test.msl/0/14\n"
                        "    First_Child = 3\n"
                        "    Next_Child = 6\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  VAR_REF = a:\n"
                        "    Start = test.msl/0/15\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 4\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  VAR_REF = b:\n"
                        "    Start = test.msl/0/17\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  VAR_REF = a:\n"
                        "    Start = test.msl/1/2\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 7\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  INFIX(+):\n"
                        "    Start = test.msl/1/4\n"
                        "    First_Child = 5\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  VAR_REF = b:\n"
                        "    Start = test.msl/1/6\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "MASK: $ $ $ $ $ $ $ $ \n"

  );
}
void test_function_no_args(T *t) {
  string code = "function void(){ }";
  string out = parse_and_show(code);
  t->assert_str_eq(out, "First Item = 1\n"
                        "\n"
                        "Node  NIL:\n"
                        "    Start = NIL\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  FUNCTION = void:\n"
                        "    Start = test.msl/0/2\n"
                        "    First_Child = 2\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  LIST:\n"
                        "    Start = test.msl/0/15\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "MASK: $ $ $ \n"

  );
}
void test_function_returns(T *t) {
  string code = "function does_return(){ return not #true }";
  string out = parse_and_show(code);
  t->assert_str_eq(out, "First Item = 1\n"
                        "\n"
                        "Node  NIL:\n"
                        "    Start = NIL\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  FUNCTION = does_return:\n"
                        "    Start = test.msl/0/2\n"
                        "    First_Child = 2\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  LIST:\n"
                        "    Start = test.msl/0/22\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 3\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  RETURN:\n"
                        "    Start = test.msl/0/26\n"
                        "    First_Child = 4\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  NOT:\n"
                        "    Start = test.msl/0/33\n"
                        "    First_Child = 5\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  LITERAL_SYMBOL = #true:\n"
                        "    Start = test.msl/0/37\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "MASK: $ $ $ $ $ $ \n"

  );
}
void test_function_left_apply(T *t) {
  string code = "a . add(1)";
  string out = parse_and_show(code);
  t->assert_str_eq(out, "First Item = 2\n"
                        "\n"
                        "Node  NIL:\n"
                        "    Start = NIL\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  VAR_REF = a:\n"
                        "    Start = test.msl/0/2\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 4\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  FN_CALL:\n"
                        "    Start = test.msl/0/6\n"
                        "    First_Child = 3\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  VAR_REF = add:\n"
                        "    Start = test.msl/0/6\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 1\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  LITERAL_INT = 1:\n"
                        "    Start = test.msl/0/10\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "MASK: $ $ $ $ $ \n"

  );
}
void test_function_right_apply(T *t) {
  string code = "a | add(1)";
  string out = parse_and_show(code);
  t->assert_str_eq(out, "First Item = 2\n"
                        "\n"
                        "Node  NIL:\n"
                        "    Start = NIL\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  VAR_REF = a:\n"
                        "    Start = test.msl/0/2\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  FN_CALL:\n"
                        "    Start = test.msl/0/6\n"
                        "    First_Child = 3\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  VAR_REF = add:\n"
                        "    Start = test.msl/0/6\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 4\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  LITERAL_INT = 1:\n"
                        "    Start = test.msl/0/10\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 1\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "MASK: $ $ $ $ $ \n"

  );
}
void test_list(T *t) {
  string code = "list() list(1,2,3) list(1)";
  string out = parse_and_show(code);
  t->assert_str_eq(out, "First Item = 1\n"
                        "\n"
                        "Node  NIL:\n"
                        "    Start = NIL\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  LIST:\n"
                        "    Start = test.msl/0/6\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 2\n"
                        "-----------------------\n"
                        "Node  LIST:\n"
                        "    Start = test.msl/0/13\n"
                        "    First_Child = 3\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 6\n"
                        "-----------------------\n"
                        "Node  LITERAL_INT = 1:\n"
                        "    Start = test.msl/0/14\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 4\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  LITERAL_INT = 2:\n"
                        "    Start = test.msl/0/16\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 5\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  LITERAL_INT = 3:\n"
                        "    Start = test.msl/0/18\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  LIST:\n"
                        "    Start = test.msl/0/25\n"
                        "    First_Child = 7\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  LITERAL_INT = 1:\n"
                        "    Start = test.msl/0/26\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "MASK: $ $ $ $ $ $ $ $ \n"

  );
}
void test_list_get(T *t) {
  string code = "at(mylist,0)";
  string out = parse_and_show(code);
  t->assert_str_eq(out, "First Item = 1\n"
                        "\n"
                        "Node  NIL:\n"
                        "    Start = NIL\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  AT:\n"
                        "    Start = test.msl/0/2\n"
                        "    First_Child = 2\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  LIST:\n"
                        "    Start = test.msl/0/4\n"
                        "    First_Child = 3\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  VAR_REF = mylist:\n"
                        "    Start = test.msl/0/5\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 4\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  LITERAL_INT = 0:\n"
                        "    Start = test.msl/0/12\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "MASK: $ $ $ $ $ \n"

  );
}
void test_list_set(T *t) {
  string code = "put(mylist,0,1)";
  string out = parse_and_show(code);
  t->assert_str_eq(out, "First Item = 1\n"
                        "\n"
                        "Node  NIL:\n"
                        "    Start = NIL\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  PUT:\n"
                        "    Start = test.msl/0/2\n"
                        "    First_Child = 2\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  LIST:\n"
                        "    Start = test.msl/0/5\n"
                        "    First_Child = 3\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  VAR_REF = mylist:\n"
                        "    Start = test.msl/0/6\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 4\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  LITERAL_INT = 0:\n"
                        "    Start = test.msl/0/13\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 5\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "Node  LITERAL_INT = 1:\n"
                        "    Start = test.msl/0/15\n"
                        "    First_Child = 0\n"
                        "    Next_Child = 0\n"
                        "    Next_Sibling = 0\n"
                        "-----------------------\n"
                        "MASK: $ $ $ $ $ $ \n"

  );
}
} // namespace
int main() {
  T t("Parser");
  t.test("literal values", test_literal);
  t.test("var def", test_var_def);
  t.test("group and prefix operator", test_group_and_prefix_operator);
  t.test("add", test_add);
  t.test("fn-call", test_fn_call);
  t.test("if", test_if);
  t.test("if-elif-elif-else", test_if_elif_elif_else);
  t.test("function", test_function);
  t.test("function no args", test_function_no_args);
  t.test("function with return", test_function_returns);
  t.test("function left apply", test_function_left_apply);
  t.test("function right apply", test_function_right_apply);
  t.test("function call after operator?", test_fn_call_2);
  t.test("list", test_list);
  t.test("get list element", test_list_get);
  t.test("set list element", test_list_set);
  return 0;
}
