#pragma once
#include "../src/preprocessor/preprocessor_token.hpp"
#include <string>
using namespace std;
inline string pptoken_to_string(const PreprocessorToken &token) {
  switch (token.tag) {
  case PpTokenTag::INT:
    return to_string(token.as.INT);
  case PpTokenTag::FLOAT:
    return to_string(token.as.FLOAT);
  case PpTokenTag::SYMBOL:
    return resolve_symbol(token.as.SYMBOL);
  case PpTokenTag::STRING:
    return "\"" + resolve_interned_string(token.as.STR) + "\"";
  case PpTokenTag::LET:
    return "let";
  case PpTokenTag::SET:
    return "set";
  case PpTokenTag::IF:
    return "if";
  case PpTokenTag::ELIF:
    return "elif";
  case PpTokenTag::ELSE:
    return "else";
  case PpTokenTag::FUNCTION:
    return "function";
  case PpTokenTag::TRY:
    return "try";
  case PpTokenTag::EXPECT:
    return "expect";
  case PpTokenTag::ASSIGN:
    return "=";
  case PpTokenTag::BROPEN:
    return "(";
  case PpTokenTag::BRCLOSE:
    return ")";
  case PpTokenTag::CURLOPEN:
    return "{";
  case PpTokenTag::CURLCLOSE:
    return "}";
  case PpTokenTag::COMMA:
    return ",";
  case PpTokenTag::DOT:
    return ".";
  case PpTokenTag::BAR:
    return "|";
  case PpTokenTag::OP_ADD:
    return "+";
  case PpTokenTag::OP_SUB:
    return "-";
  case PpTokenTag::OP_MUL:
    return "*";
  case PpTokenTag::OP_DIV:
    return "/";
  case PpTokenTag::OP_MOD:
    return "mod";
  case PpTokenTag::OP_EQ:
    return "==";
  case PpTokenTag::OP_NEQ:
    return "!=";
  case PpTokenTag::OP_NOT:
    return "not";
  case PpTokenTag::OP_OR:
    return "or";
  case PpTokenTag::OP_AND:
    return "and";
  case PpTokenTag::OPERATOR_LT:
    return "<";
  case PpTokenTag::OPERATOR_LTE:
    return "<=";
  case PpTokenTag::OPERATOR_GT:
    return ">";
  case PpTokenTag::OPERATOR_GTE:
    return ">=";
  case PpTokenTag::OPERATOR_STRCONCAT:
    return "<>";
  case PpTokenTag::IDENTIFIER:
    return resolve_interned_string(token.as.IDENTIFIER);
  case PpTokenTag::RETURN:
    return "return";
  case PpTokenTag::INCLUDE_MACRO:
    return "MACRO(-include)";
  case PpTokenTag::DEFINE_MACRO:
    return "MACRO(-define)";
  case PpTokenTag::FSET_MACRO:
    return "MACRO(-fset)";
  case PpTokenTag::FUNSET_MACRO:
    return "MACRO(-funset)";
  case PpTokenTag::IFFSET_MACRO:
    return "MACRO(-iffset)";
  case PpTokenTag::IFNFSET_MACRO:
    return "MACRO(-ifnfset)";
  case PpTokenTag::ENDIF_MACRO:
    return "MACRO(-endif)";
  case PpTokenTag::BRACKETOPEN:
    return "[";
  case PpTokenTag::BRACKETCLOSE:
    return "]";
  case PpTokenTag::FOR:
    return "for";
  case PpTokenTag::IN:
    return "in";
  }
}
